### ISSUE TITLE
Compile error: unknown type name 'rd_ts_t'

### ISSUE THREAD

**Issue by JeffLiang2018** [confluentinc/confluent-kafka-go#1080]
Description
===========
When I built my go image I saw the following error:
```
#12 151.6 # arubanetworks.com/vendor/github.com/confluentinc/confluent-kafka-go/kafka
#12 151.6 In file included from ./select_rdkafka.h:30,
#12 151.6                  from src/arubanetworks.com/vendor/github.com/confluentinc/confluent-kafka-go/kafka/****api.go:28:
#12 151.6 /usr/include/librdkafka/rdkafka_mock.h:374:56: error: unknown type name 'rd_ts_t'
#12 151.6   374 | rd_kafka_mock_request_new(int32_t id, int16_t api_key, rd_ts_t timestamp);
#12 151.6       |                                                        ^~~~~~~
#12 151.6 /usr/include/librdkafka/rdkafka_mock.h:400:11: error: unknown type name 'rd_ts_t'
#12 151.6   400 | RD_EXPORT rd_ts_t
#12 151.6       |           ^~~~~~~
```
It error results from:
- `confluent-kafka-go/kafka/select_rdkafka.h` imported file `rdkafka_mock.h` 
- `rdkafka_mock.h` is in this [location](https://github.com/confluentinc/librdkafka/blob/master/src/rdkafka_mock.h)
- In line 374 of `rdkafka_mock.h`, define function `rd_kafka_mock_request_new(int32_t id, int16_t api_key, rd_ts_t timestamp);`
- `rd_ts_t` is not defined.

How to reproduce
================
- Set Go111MODULE to be off.
- Set confluentic/confluent-kafka-go/kafka as a 3rd party library
- Add `download confluentinc/librdkafka` and set up configuration as the [guideline](https://github.com/confluentinc/librdkafka#installation) 
-  Build a docker image.

How to fix:
=================
- Copy and paste `rd_types.h` to `confluent-kafka-go/kafka/librdkafka_vendor/rdtypes.h`
- Modify `confluent-kafka-go/kafka/select_rdkafka.h` as following: (only include the h files under `librdkafka`)
```shell
#include "librdkafka_vendor/rdtypes.h"
#include "librdkafka_vendor/rdkafka.h"
#include "librdkafka_vendor/rdkafka_mock.h"
``` 

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [x] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`
 - [x] Operating system: Ubuntu 20.x
 - [x] Provide client logs (with `"debug": ".."` as necessary)
 - [x] Provide broker log excerpts
 - [x] Critical issue

**Comment by milindl** [comment]
Should be fixed now, please tell me if this occurs now on the latest master.

**Comment by JeffLiang2018** [comment]
When you said `v2.2` and `v2.3`, do you mean these 2 branches?
```
liangj@Jeffs-MacBook-Pro-4 confluent-kafka-go % git branch --all | grep -i v2.
  remotes/origin/import_v2.0.0-RC3
  remotes/origin/import_v2.0.0-RC4
```
Since I can't find any particular branches named `v2.2` or `v2.3`.
Could you post the exact branch in the thread, please? 
Thank you very much.

**Comment by JeffLiang2018** [comment]
Oh, `v2.2.0` is a tag, although I am still unable to see `v2.3`. 
Anyway, thank you very much for your help.

**Comment by milindl** [comment]
Unfortunately, the tag 2.3 is not ready yet. It should be ready in a few days when we make the next release
Right now, the error is fixed in the latest master.

**Comment by JeffLiang2018** [comment]
I see. I would use tag 2.2
Thank you very much for your help.
